package org.acg12.conf.event;

public enum CommonEnum {
    COMMON_DEF,
    COMMON_UPDATA_USER,
    COMMON_UPDATA_USER_LOAD,

    COMMON_UPDATA_GROUP_UNEXCUSE,
    COMMON_UPDATA_CONVERSATION_LIST,
    COMMON_UPDATA_CONVERSATION_RESET_LOGIN,
    COMMON_UPDATA_MEETING_NATION,

    // 扫描激活
    COMMON_TASK_TERMINAL,
    // 终端维护
    COMMON_MAINTAIN_TERMINAL,
}
